# Generated by Django 5.2.6 on 2025-09-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audio_video'),
    ]

    operations = [
    ]
